Repository navarasu/opencv-log, pull requests merged in 2020-05, with the labels that each got.

#17 #16 Enable log path for outside config and Enable log rotation for ea…
  cvlog/__init__.py
  cvlog/config.py
  cvlog/html_logger.py
  cvlog/log.py
  cvtest/reporter.py
  tests/test_html_loggger.py
  tests/test_log.py
  tests/test_log_rotation.py
Labels: enhancement

#19 #16 Updated docs for new config
  docs/configuration.rst
  docs/index.rst
  docs/logging.rst
Labels: documentation

#22 Log Hough circles
  cvlog/__init__.py
  cvlog/log.py
  docs/logging.rst
  tests/data/board.jpg
  tests/data/expected/houghcircle_img.txt
  tests/test_log.py
Labels: enhancement

#31 Fixed the invalid no data logged message notification
  cvlog/html_logger.py
  tests/test_log.py
Labels: bug

#32 #23 Added option to log contours
  cvlog/__init__.py
  cvlog/log.py
  docs/logging.rst
  tests/data/contour.jpg
  tests/data/expected/contour.txt
  tests/test_log.py
Labels: enhancement

#33 #27 Add Contributions.md and github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTION.md
  README.rst
Labels: documentation
